### ISSUE TITLE
Broken root Makefile

### ISSUE THREAD

**Issue by slivingston** [JPLOpenSource/SCA#1]
Running `make` in the root of the source tree fails on Ubuntu 14.04 with GNU Make 3.81, Linux 3.13.0, gcc 4.8.2, javac 1.7.0_75. I suspect that it can be corrected by changing `QF-C` to `QF_C`. Moreover, there are several subdirectories that have Makefiles and thus which I would expect to also be included in the `modules` variable of the root Makefile. Thus, I recommend

```
modules = autocoder QF_Cpp QF_Cm QF_C
```

**Comment by ljreder** [comment]
Fixed top level Makefile.
